apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blocker-service.fullname" . }}
  labels:
    {{- include "blocker-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blocker-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blocker-service.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.global.metrics.prometheusPath | default "/actuator/prometheus" | quote }}
        prometheus.io/port: {{ .Values.service.port | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ include "blocker-service.fullname" . }}-db:5432/{{ .Values.db.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "blocker-service.fullname" . }}-db-secret
                  key: password
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.auth.issuerUri }}
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: {{ .Values.global.tracing.zipkinEndpoint | default "http://zipkin.observability.svc.cluster.local:9411/api/v2/spans" | quote }}
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,metrics,prometheus"
            - name: LOGS_BOOTSTRAP_SERVERS
              value: {{ .Values.global.logging.bootstrapServers | default "kafka.kafka.svc.cluster.local:9092" | quote }}
            - name: LOGS_TOPIC
              value: {{ .Values.global.logging.topic | default "service-logs" | quote }}
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: {{ .Chart.Name | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
