apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blocker-service.fullname" . }}-db-secret
  labels:
    {{- include "blocker-service.labels" . | nindent 4 }}
type: Opaque
data:
  password: YmFua19hcHBfcGFzc3dvcmQ=

