server:
  port: 8085

spring:
  application:
    name: auth-server
  cloud:
    config:
      enabled: false
      fail-fast: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app_db
    username: bank_app_user
    password: bank_app_password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      authorization-server:
        issuer: http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${MANAGEMENT_METRICS_TAGS_ENVIRONMENT:dev}
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin.observability.svc.cluster.local:9411/api/v2/spans}

logging:
  time-zone: Europe/Moscow
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
