server:
  port: 8087

spring:
  application:
    name: exchange-service
  autoconfigure:
    exclude:
      - io.github.resilience4j.springboot3.fallback.autoconfigure.FallbackAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: exchange-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: io.github.danjos.mybankapp.exchange.kafka.ExchangeRateEvent
        spring.json.use.type.headers: false
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app_db
    username: bank_app_user
    password: bank_app_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: exchange_schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  time-zone: Europe/Moscow
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    io.github.danjos.mybankapp.exchange: DEBUG

kafka:
  topics:
    exchange-rates: exchange-rates
