global:
  env: dev

replicaCount: 1

image:
  repository: cash-service
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8082

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

db:
  image: postgres:13
  port: 5432
  username: bank_app_user
  database: bank_app_db
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  persistence:
    size: 1Gi
    storageClass: standard

auth:
  issuerUri: http://auth-server:8085

