pipeline {
    agent any

    environment {
        KAFKA_RELEASE_NAME = 'kafka'
        KAFKA_NAMESPACE = 'kafka'
        KAFKA_CHART = 'oci://registry-1.docker.io/bitnamicharts/kafka'
        KAFKA_VERSION = '30.1.5'
        KAFKA_VALUES = 'helm/kafka/values-standalone.yaml'
        KAFKA_VALUES_PROD = 'helm/kafka/values-standalone-prod.yaml'
        OBSERVABILITY_NAMESPACE = 'observability'
        ZIPKIN_RELEASE_NAME = 'zipkin'
        ZIPKIN_CHART = 'oci://registry-1.docker.io/bitnamicharts/openzipkin'
        ZIPKIN_VERSION = '1.0.0'
        PROMETHEUS_STACK_RELEASE_NAME = 'kube-prometheus-stack'
        PROMETHEUS_STACK_CHART = 'oci://registry-1.docker.io/bitnamicharts/kube-prometheus'
        PROMETHEUS_STACK_VERSION = '55.0.0'
        ELK_RELEASE_NAME = 'elk'
        ELASTICSEARCH_CHART = 'oci://registry-1.docker.io/bitnamicharts/elasticsearch'
        ELASTICSEARCH_VERSION = '21.0.0'
        KIBANA_CHART = 'oci://registry-1.docker.io/bitnamicharts/kibana'
        KIBANA_VERSION = '12.0.0'
    }

    stages {
        stage('Create Kafka Namespace') {
            steps {
                echo 'Creating Kafka namespace...'
                sh '''
                    kubectl create namespace ${KAFKA_NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -
                '''
            }
        }

        stage('Deploy Kafka to Test') {
            steps {
                echo 'Deploying Apache Kafka to Test environment...'
                script {
                    sh """
                        helm upgrade --install ${KAFKA_RELEASE_NAME} ${KAFKA_CHART} \
                        --version ${KAFKA_VERSION} \
                        --namespace ${KAFKA_NAMESPACE} \
                        --create-namespace \
                        -f ${KAFKA_VALUES} \
                        --wait \
                        --timeout 10m
                    """
                }
            }
        }

        stage('Wait for Kafka Ready') {
            steps {
                echo 'Waiting for Kafka to be ready...'
                sh '''
                    kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=kafka \
                    --namespace ${KAFKA_NAMESPACE} \
                    --timeout=300s
                '''
            }
        }

        stage('Create Kafka Topics') {
            steps {
                echo 'Creating Kafka topics...'
                script {
                    def topics = [
                        [name: 'account-created', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'account-updated', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'deposit-completed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'withdrawal-completed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'transfer-initiated', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'transfer-completed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'transfer-failed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'notification-event', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'exchange-rates', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'application-logs', partitions: 3, rf: 1, minInsync: 1]
                    ]

                    topics.each { topicCfg ->
                        sh """
                            kubectl exec -n ${KAFKA_NAMESPACE} \$(kubectl get pod -n ${KAFKA_NAMESPACE} -l app.kubernetes.io/name=kafka,app.kubernetes.io/instance=${KAFKA_RELEASE_NAME} -o jsonpath='{.items[0].metadata.name}') -- \\
                            kafka-topics.sh --create \\
                            --if-not-exists \\
                            --bootstrap-server localhost:9092 \\
                            --topic ${topicCfg.name} \\
                            --partitions ${topicCfg.partitions} \\
                            --replication-factor ${topicCfg.rf} \\
                            --config retention.ms=604800000 \\
                            --config min.insync.replicas=${topicCfg.minInsync} || true
                        """
                    }
                }
            }
        }

        stage('Verify Topics') {
            steps {
                echo 'Verifying Kafka topics...'
                sh """
                    kubectl exec -n ${KAFKA_NAMESPACE} \$(kubectl get pod -n ${KAFKA_NAMESPACE} -l app.kubernetes.io/name=kafka,app.kubernetes.io/instance=${KAFKA_RELEASE_NAME} -o jsonpath='{.items[0].metadata.name}') -- \
                    kafka-topics.sh --list --bootstrap-server localhost:9092
                """
            }
        }

        stage('Create Observability Namespace') {
            steps {
                echo 'Creating observability namespace...'
                sh """
                    kubectl create namespace ${OBSERVABILITY_NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -
                """
            }
        }

        stage('Deploy Zipkin') {
            steps {
                echo 'Deploying Zipkin for distributed tracing...'
                script {
                    sh """
                        helm upgrade --install ${ZIPKIN_RELEASE_NAME} ${ZIPKIN_CHART} \
                        --version ${ZIPKIN_VERSION} \
                        --namespace ${OBSERVABILITY_NAMESPACE} \
                        --create-namespace \
                        --set service.type=ClusterIP \
                        --set service.port=9411 \
                        --wait \
                        --timeout 5m
                    """
                }
            }
        }

        stage('Deploy Prometheus and Grafana Stack') {
            steps {
                echo 'Deploying Prometheus and Grafana monitoring stack...'
                script {
                    sh """
                        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
                        helm repo update
                        helm upgrade --install ${PROMETHEUS_STACK_RELEASE_NAME} prometheus-community/kube-prometheus-stack \
                        --version ${PROMETHEUS_STACK_VERSION} \
                        --namespace ${OBSERVABILITY_NAMESPACE} \
                        --create-namespace \
                        --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
                        --set grafana.service.type=ClusterIP \
                        --set grafana.adminPassword=admin \
                        --wait \
                        --timeout 10m
                    """
                }
            }
        }

        stage('Deploy ELK Stack') {
            steps {
                echo 'Deploying ELK stack for log aggregation...'
                script {
                    // Deploy Elasticsearch
                    sh """
                        helm upgrade --install elasticsearch ${ELASTICSEARCH_CHART} \
                        --version ${ELASTICSEARCH_VERSION} \
                        --namespace ${OBSERVABILITY_NAMESPACE} \
                        --set global.kibanaEnabled=true \
                        --set master.replicas=1 \
                        --set data.replicas=1 \
                        --set coordinating.replicas=1 \
                        --wait \
                        --timeout 10m
                    """
                    
                    // Deploy Kibana
                    sh """
                        helm upgrade --install kibana ${KIBANA_CHART} \
                        --version ${KIBANA_VERSION} \
                        --namespace ${OBSERVABILITY_NAMESPACE} \
                        --set elasticsearch.hosts[0]=elasticsearch:9200 \
                        --set service.type=ClusterIP \
                        --wait \
                        --timeout 5m
                    """
                }
            }
        }

        stage('Deploy Logstash') {
            steps {
                echo 'Deploying Logstash for Kafka to Elasticsearch pipeline...'
                script {
                    sh """
                        helm upgrade --install logstash ./helm/logstash \
                        --namespace ${OBSERVABILITY_NAMESPACE} \
                        --set kafka.bootstrapServers=kafka.kafka.svc.cluster.local:9092 \
                        --set elasticsearch.host=elasticsearch.observability.svc.cluster.local \
                        --wait \
                        --timeout 10m
                    """
                }
            }
        }

        stage('Deploy Kafka to Production') {
            input {
                message "Deploy Kafka to Production?"
                ok "Yes, deploy"
            }
            steps {
                echo 'Deploying Apache Kafka to Production environment...'
                script {
                    sh """
                        helm upgrade --install ${KAFKA_RELEASE_NAME} ${KAFKA_CHART} \
                        --version ${KAFKA_VERSION} \
                        --namespace ${KAFKA_NAMESPACE} \
                        --create-namespace \
                        -f ${KAFKA_VALUES} \
                        -f ${KAFKA_VALUES_PROD} \
                        --wait \
                        --timeout 15m
                    """
                }
                echo 'Creating production topics...'
                script {
                    def topics = [
                        [name: 'account-created', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'account-updated', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'deposit-completed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'withdrawal-completed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'transfer-initiated', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'transfer-completed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'transfer-failed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'notification-event', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'exchange-rates', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'application-logs', partitions: 6, rf: 3, minInsync: 2]
                    ]
                    
                    topics.each { topicCfg ->
                        sh """
                            kubectl exec -n ${KAFKA_NAMESPACE} \$(kubectl get pod -n ${KAFKA_NAMESPACE} -l app.kubernetes.io/name=kafka,app.kubernetes.io/instance=${KAFKA_RELEASE_NAME} -o jsonpath='{.items[0].metadata.name}') -- \\
                            kafka-topics.sh --create \\
                            --if-not-exists \\
                            --bootstrap-server localhost:9092 \\
                            --topic ${topicCfg.name} \\
                            --partitions ${topicCfg.partitions} \\
                            --replication-factor ${topicCfg.rf} \\
                            --config retention.ms=604800000 \\
                            --config min.insync.replicas=${topicCfg.minInsync} || true
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Kafka deployment pipeline completed.'
        }
        success {
            echo 'Kafka deployed successfully!'
        }
        failure {
            echo 'Kafka deployment failed!'
        }
    }
}

