pipeline {
    agent any

    environment {
        KAFKA_RELEASE_NAME = 'kafka'
        KAFKA_NAMESPACE = 'kafka'
        KAFKA_CHART = 'bitnami/kafka'
        KAFKA_VERSION = '30.1.5'
        KAFKA_VALUES = 'helm/kafka/values.yaml'
        KAFKA_VALUES_PROD = 'helm/kafka/values-prod.yaml'
    }

    stages {
        stage('Add Bitnami Helm Repository') {
            steps {
                echo 'Adding Bitnami Helm repository...'
                sh '''
                    helm repo add bitnami https://charts.bitnami.com/bitnami
                    helm repo update
                '''
            }
        }

        stage('Create Kafka Namespace') {
            steps {
                echo 'Creating Kafka namespace...'
                sh '''
                    kubectl create namespace ${KAFKA_NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -
                '''
            }
        }

        stage('Deploy Kafka to Test') {
            steps {
                echo 'Deploying Apache Kafka to Test environment...'
                script {
                    sh """
                        helm upgrade --install ${KAFKA_RELEASE_NAME} ${KAFKA_CHART} \
                        --version ${KAFKA_VERSION} \
                        --namespace ${KAFKA_NAMESPACE} \
                        --create-namespace \
                        -f ${KAFKA_VALUES} \
                        --wait \
                        --timeout 10m
                    """
                }
            }
        }

        stage('Wait for Kafka Ready') {
            steps {
                echo 'Waiting for Kafka to be ready...'
                sh '''
                    kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=kafka \
                    --namespace ${KAFKA_NAMESPACE} \
                    --timeout=300s
                '''
            }
        }

        stage('Create Kafka Topics') {
            steps {
                echo 'Creating Kafka topics...'
                script {
                    def topics = [
                        [name: 'account-created', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'account-updated', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'deposit-completed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'withdrawal-completed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'transfer-initiated', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'transfer-completed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'transfer-failed', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'notification-event', partitions: 3, rf: 1, minInsync: 1],
                        [name: 'exchange-rates', partitions: 3, rf: 1, minInsync: 1]
                    ]

                    topics.each { topicCfg ->
                        sh """
                            kubectl exec -n ${KAFKA_NAMESPACE} ${KAFKA_RELEASE_NAME}-controller-0 -- \
                            kafka-topics.sh --create \
                            --if-not-exists \
                            --bootstrap-server localhost:9092 \
                            --topic ${topicCfg.name} \
                            --partitions ${topicCfg.partitions} \
                            --replication-factor ${topicCfg.rf} \
                            --config retention.ms=604800000 \
                            --config min.insync.replicas=${topicCfg.minInsync} || true
                        """
                    }
                }
            }
        }

        stage('Verify Topics') {
            steps {
                echo 'Verifying Kafka topics...'
                sh """
                    kubectl exec -n ${KAFKA_NAMESPACE} ${KAFKA_RELEASE_NAME}-controller-0 -- \
                    kafka-topics.sh --list --bootstrap-server localhost:9092
                """
            }
        }

        stage('Deploy Kafka to Production') {
            input {
                message "Deploy Kafka to Production?"
                ok "Yes, deploy"
            }
            steps {
                echo 'Deploying Apache Kafka to Production environment...'
                script {
                    sh """
                        helm upgrade --install ${KAFKA_RELEASE_NAME} ${KAFKA_CHART} \
                        --version ${KAFKA_VERSION} \
                        --namespace ${KAFKA_NAMESPACE} \
                        --create-namespace \
                        -f ${KAFKA_VALUES} \
                        -f ${KAFKA_VALUES_PROD} \
                        --wait \
                        --timeout 15m
                    """
                }
                echo 'Creating production topics...'
                script {
                    def topics = [
                        [name: 'account-created', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'account-updated', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'deposit-completed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'withdrawal-completed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'transfer-initiated', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'transfer-completed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'transfer-failed', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'notification-event', partitions: 6, rf: 3, minInsync: 2],
                        [name: 'exchange-rates', partitions: 6, rf: 3, minInsync: 2]
                    ]
                    
                    topics.each { topicCfg ->
                        sh """
                            kubectl exec -n ${KAFKA_NAMESPACE} ${KAFKA_RELEASE_NAME}-controller-0 -- \
                            kafka-topics.sh --create \
                            --if-not-exists \
                            --bootstrap-server localhost:9092 \
                            --topic ${topicCfg.name} \
                            --partitions ${topicCfg.partitions} \
                            --replication-factor ${topicCfg.rf} \
                            --config retention.ms=604800000 \
                            --config min.insync.replicas=${topicCfg.minInsync} || true
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Kafka deployment pipeline completed.'
        }
        success {
            echo 'Kafka deployed successfully!'
        }
        failure {
            echo 'Kafka deployment failed!'
        }
    }
}

