server:
  port: 8088

spring:
  application:
    name: exchange-generator-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false

services:
  exchange:
    url: http://localhost:8087

kafka:
  topics:
    exchange-rates: exchange-rates

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin.observability.svc.cluster.local:9411/api/v2/spans}

logging:
  time-zone: Europe/Moscow
  level:
    org.springframework.web: DEBUG
    io.github.danjos.mybankapp.exchangegenerator: DEBUG
