server:
  port: 8088

spring:
  application:
    name: exchange-generator-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false

services:
  exchange:
    url: http://localhost:8087

kafka:
  topics:
    exchange-rates: exchange-rates

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  time-zone: Europe/Moscow
  level:
    org.springframework.web: DEBUG
    io.github.danjos.mybankapp.exchangegenerator: DEBUG
