apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transfer-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transfer-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ include "transfer-service.fullname" . }}-db:5432/{{ .Values.db.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "transfer-service.fullname" . }}-db-secret
                  key: password
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.auth.issuerUri }}
            - name: SERVICES_ACCOUNTS_URL
              value: {{ .Values.services.accounts }}
            - name: SERVICES_EXCHANGE_URL
              value: {{ .Values.services.exchange }}
            - name: SERVICES_BLOCKER_URL
              value: {{ .Values.services.blocker }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

