apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-ui.fullname" . }}
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "front-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_BANK_APP_AUTHORIZATION_URI
              value: {{ .Values.auth.issuerUri }}/oauth2/authorize
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_BANK_APP_TOKEN_URI
              value: {{ .Values.auth.issuerUri }}/oauth2/token
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_BANK_APP_USER_INFO_URI
              value: {{ .Values.auth.issuerUri }}/userinfo
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

