server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: true
      fail-fast: true
      uri: http://localhost:8888
    gateway:
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=2
        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/api/cash/**
          filters:
            - StripPrefix=2
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=2
        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2
        - id: front-ui
          uri: lb://front-ui
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      accounts-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
      cash-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
      transfer-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
      notifications-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
  retry:
    instances:
      accounts-service:
        max-attempts: 3
        wait-duration: 1s
      cash-service:
        max-attempts: 3
        wait-duration: 1s
      transfer-service:
        max-attempts: 3
        wait-duration: 1s
      notifications-service:
        max-attempts: 3
        wait-duration: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
