image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: "8.11.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 9200

kibana:
  enabled: true
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: "8.11.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

