server:
  port: 8086

spring:
  application:
    name: front-ui
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app_db
    username: bank_app_user
    password: bank_app_password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          bank-app:
            client-id: front-ui-client
            client-secret: front-ui-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: read,write
        provider:
          bank-app:
            authorization-uri: http://auth-server:8085/oauth2/authorize
            token-uri: http://auth-server:8085/oauth2/token
            user-info-uri: http://auth-server:8085/userinfo
            user-name-attribute: sub
    user:
      name-attribute: sub
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  zipkin:
    base-url: http://zipkin:9411

logging:
  time-zone: Europe/Moscow
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
