server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bank_app_db
    username: bank_app_user
    password: bank_app_password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        provider:
          bank-app:
            authorization-uri: http://my-bank-app-auth-server:8085/oauth2/authorize
            token-uri: http://my-bank-app-auth-server:8085/auth/token
            user-info-uri: http://my-bank-app-auth-server:8085/userinfo

gateway:
  url: http://gateway:8080
