global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/kibana
  tag: 9.1.2-debian-12-r0
  pullPolicy: IfNotPresent

elasticsearch:
  hosts:
    - elasticsearch-master.observability.svc.cluster.local
  port: 9200

service:
  type: ClusterIP

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 8

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 8


