elasticsearch:
  hosts:
    - elasticsearch-master.observability.svc.cluster.local
  port: 9200

service:
  type: ClusterIP

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi


