apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exchange-generator-service.fullname" . }}
  labels:
    {{- include "exchange-generator-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "exchange-generator-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "exchange-generator-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVICES_EXCHANGE_URL
              value: {{ .Values.services.exchange.url }}
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: SPRING_APPLICATION_JSON
              value: '{"spring": {"config": {"import": "optional:file:./"}}}'
            - name: SPRING_CLOUD_CONFIG_URI
              value: ""
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
