apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exchange-generator-service.fullname" . }}
  labels:
    {{- include "exchange-generator-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "exchange-generator-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "exchange-generator-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVICES_EXCHANGE_URL
              value: {{ .Values.services.exchange }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

