spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bank_app_db
    username: bank_app_user
    password: bank_app_password
  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092
