apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accounts-service.fullname" . }}
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "accounts-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "accounts-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers | quote }}
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ include "accounts-service.fullname" . }}-db:5432/{{ .Values.db.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-service.fullname" . }}-db-secret
                  key: password
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://my-bank-app-auth-server:8085
            {{- if .Values.observability.enabled }}
            - name: SPRING_ZIPKIN_BASE_URL
              value: {{ .Values.observability.zipkinUrl | default "http://zipkin.observability.svc.cluster.local:9411" | quote }}
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,metrics,prometheus"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

