apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch-simple.fullname" . }}
  labels:
    {{- include "elasticsearch-simple.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "elasticsearch-simple.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elasticsearch-simple.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx512m"
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          emptyDir: {}
---
{{- if .Values.kibana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch-simple.fullname" . }}-kibana
  labels:
    {{- include "elasticsearch-simple.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "elasticsearch-simple.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kibana
  template:
    metadata:
      labels:
        {{- include "elasticsearch-simple.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://{{ include "elasticsearch-simple.fullname" . }}:9200"
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
{{- end }}

