server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  datasource:
    url: ""
    driver-class-name: ""
  cloud:
    config:
      server:
        native:
          search-locations: file:classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,configprops
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG
