# Exchange Generator Service specific configuration
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8085

# Exchange generator service specific settings
exchange-generator:
  service:
    name: exchange-generator-service
    port: 8088
  schedule:
    rate-update-interval: 1s
  resilience4j:
    circuit-breaker:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 30s
      sliding-window-size: 10
    retry:
      max-attempts: 3
      wait-duration: 1s

# Service URLs for inter-service communication
services:
  exchange:
    url: http://exchange-service:8087

logging:
  time-zone: Europe/Moscow
  level:
    org.springframework.web: DEBUG
    io.github.danjos.mybankapp.exchangegenerator: DEBUG

