apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash-service.fullname" . }}-db-secret
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Default password 'bank_app_password' encoded in base64
  password: YmFua19hcHBfcGFzc3dvcmQ=
