apiVersion: v1
kind: Service
metadata:
  name: {{ include "cash-service.fullname" . }}-db
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: {{ .Values.db.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "cash-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  clusterIP: None

