apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exchange-service.fullname" . }}-db-secret
  labels:
    {{- include "exchange-service.labels" . | nindent 4 }}
type: Opaque
data:
  password: YmFua19hcHBfcGFzc3dvcmQ=

